
node_config: [[127.0.0.1, username1, passwd1]]#, [ip2, username2, passwdh2]]
#test_node_config: [["ip", "username", "passwd"]]

end_flag: True
task: 'train'
save_interval:
  default: 50
  PPO: 5
  IMPALA: 5
  DQN: 100

config_dir: 'examples'
#single_case: "examples/pendulum_ppo.yaml"
#single_case: "examples/cartpole_ppo.yaml"
#single_case: "examples/cartpole_dqn.yaml"
#single_case: "examples/pong_ppo.yaml"
#single_case: "examples/pong_dqn.yaml"
#single_case: "examples/qbert_impala.yaml"
#single_case: "examples/breakout_impala.yaml"
#single_case: "examples/breakout_ppo.yaml"
